### PR TITLE
Give the possibility to supply a custom label generator for pie charts

### PR DESCRIPTION
**Pull request by ggiambo**

### CODE REVIEW

**Comment by timmolter** [comment]
Please add a demo.

**Comment by ggiambo** [comment]
> Please add a demo.

Done, see existing PieChart02.

If you think it could be useful, I can try to expand the custom label generator to function for all the chart types.

**Comment by ggiambo** [comment]
@timmolter is the demo OK or are you expecting something else?

**Comment by timmolter** [comment]
I appreciate the idea and effort, but the way you implemented it is different than we have for other chart types: through the styler:
```
 chart
        .getStyler()
        .setCustomCursorXDataFormattingFunction(
```

**Pull request merged**
