### PR TITLE
Mrcjkb/bar_chart_y_tick_bugfix

### PR DESCRIPTION
**Pull request by MrcJkb**
This PR fixes a bug in the calculation of Y ticks for bar charts.

**The bug**
If all Y values in the chart are > 0, then the minValue of the Y axis is set to the min value of the data, and not zero (and vice versa for bar charts with only negative values). This makes sense for a line chart, but not for a bar chart. You can reproduce the bug by running the "BarChart01" demo.

**The fix**
Under the following conditions, set the Y axis min value to 0:

- The axis direction is Y
- The styler is a `CategoryStyler`
- The min value is > 0

Under the following conditions, set the Y axis max value to 0:

- The axis direction is Y
- The styler is a `CategoryStyler`
- the max value is < 0

I also added in some null checks to the streams in `Axis#getAxisTickCalculator` from my last PR.

### CODE REVIEW

**Comment by timmolter** [comment]
@MrcJkb There's a report of a bug in the Y-Axis calculation in the recent release.

https://github.com/knowm/XChart/issues/530

I also ran the XChart demo and noticed that BarChart03, which is also a "stacked" bar chart has a rendering error.

Screen Shot 2020-11-26 at 9 52 50 AM

Would you be willing to look into this issue and possibly submit a fix?

**Comment by timmolter** [comment]
FYI here's what it looked like at the 3.6.5 release.

Screen Shot 2020-11-26 at 10 09 31 AM

**Comment by MrcJkb** [comment]
Sure :)

**Comment by timmolter** [comment]
Thanks, it works now!

**Pull request merged**
