### PR TITLE
[resolves #249] Logarithmic Y-axis on Category Chart broken?

### LINKED ISSUE #249: Logarithmic Y-axis on Category Chart broken?
The [Logarithmic Line Chart](https://knowm.org/open-source/xchart/xchart-example-code/) works as expected and gives a chart with straight line.
However, simply substituting XYChart for CategoryChart gives a chart with the bars completely off; it seems as they are actually still linearly scaled, whereas the y axis labels are correct:

Linear scale: 
xchart-categorychart-linearscale

Log scale:
xchart-categorychart-logscale

Apparently this issue exists in all version down to at least version 3.1.0.

```java
/**
 * Logarithmic Y-Axis
 * 
 * Demonstrates the following:
 * <ul>
 * <li>Logarithmic Y-Axis
 * <li>Building a Chart with ChartBuilder
 * <li>Place legend at Inside-NW position
 */
public class CategoryChart01 {

  public static void main(String[] args) {

	CategoryChart01 exampleChart = new CategoryChart01();
	CategoryChart chart = exampleChart.getChart();
    new SwingWrapper<CategoryChart>(chart).displayChart();
  }

  public CategoryChart getChart() {

    // generates Log data
    List<Integer> xData = new ArrayList<Integer>();
    List<Double> yData = new ArrayList<Double>();
    for (int i = -3; i <= 3; i++) {
      xData.add(i);
      yData.add(Math.pow(10, i));
    }

    // Create Chart
//    XYChart chart = new XYChartBuilder().width(800).height(600).title("Powers of Ten").xAxisTitle("Power").yAxisTitle("Value").build();
    CategoryChart chart = new CategoryChartBuilder().width(800).height(600).title("Powers of Ten").xAxisTitle("Power").yAxisTitle("Value").build();

    // Customize Chart
    chart.getStyler().setChartTitleVisible(true);
    chart.getStyler().setLegendPosition(LegendPosition.InsideNW);
    chart.getStyler().setYAxisLogarithmic(true);
    
    chart.getStyler().setYAxisMin(0.001);
    chart.getStyler().setYAxisMax(1000.0);

    // Series
    chart.addSeries("10^x", xData, yData);

    return chart;
  }
}
```

### PR DESCRIPTION
**Pull request by Mr14huashao**
@timmolter 
hi,tim
I have added a new method to calculate the percentage of "yTop" in "yMin" to "yMax".The drawing results are as follows:

Linear scale:
Screenshot_2019-11-12_17-23-22

Log scale:
Screenshot_2019-11-12_17-21-00

```java
// The value of yAxisMin and yAxisMax must be 10 to zhe power of, and n is an Integer. 
chart.getStyler().setYAxisMin(0.001);
chart.getStyler().setYAxisMax(1000.0);
```

### CODE REVIEW

**Comment by timmolter** [comment]
What problem does this solve exactly?

**Comment by timmolter** [comment]
Could you push the code for that bar chart with log data that you show here please?

**Comment by Mr14huashao** [comment]
The logarithmic and non-logarithmic graphics are identical before they are modified.
Should the value of yData correspond to the value on the y-axis?
For logarithmic graphs, the value of yData is recalculated at the height of the y-axis, allowing the value of yData to be displayed in the corresponding range.

**Comment by Mr14huashao** [comment]
@timmolter 

Sorry, I didn't understand what you meant last time.
Reading the code, we found that CategoryChart draws content in two ways
```java
if (CategorySeriesRenderStyle.Bar.equals(stylerCategory.getDefaultSeriesRenderStyle())
	|| CategorySeriesRenderStyle.Stick.equals(stylerCategory.getDefaultSeriesRenderStyle())) {
  this.plotContent = new PlotContent_Category_Bar<ST, S>(chart);
} else {
  this.plotContent = new PlotContent_Category_Line_Area_Scatter<ST, S>(chart);
}
```
What I modified is PlotContent_Category_Bar, PlotContent_Category_Line_Area_Scatter originally supports logarithms, and the implementation is different.
I am going to refer to PlotContent_Category_Line_Area_Scatter and push the code again.

**Pull request closed without merging**
