### PR TITLE
Chart.java & AxisTitle.java - color properties for each `Y-Axis-GroupTitle`...

### PR DESCRIPTION
**Pull request by gibhub-src**
…(extends naming with coloring). Would be great to be able to set additional Y-Axis properties.

### CODE REVIEW

**Comment by gibhub-src** [comment]
Sorry didn't figure out to create a separate branch, but it is just the AxisTitle. Should be straight forward. For the `per-Axis`-changes will make sure it is on a different `Feature-branch`.
Thank you!

**Comment by Mr14huashao** [comment]
Review the PR codes, I think there is no problem.

The first commit has already implemented this function to set the Y-axis title and multiple Y-axis title colors.

You submitted three issues(#404 #405 #406 ) for this function

**Comment by timmolter** [comment]
Let's not put these demo charts in `XChartDemo.java ` but under `org.knowm.xchart.standalone.issues`.

**Comment by timmolter** [comment]
Could you also post images of the charts here in this thread??

**Comment by gibhub-src** [comment]
Hello @timmolter & @Mr14huashao
sorry I am not sure, am I supposed to do something or was it something between you both.
I could not know for sure, if I am the addressee. Sorry :)

**Comment by timmolter** [comment]
@gibhub-src I'm waiting for you to rewrite the code according to my comment above and also to post screenshots as also requested above in a separate comment.

**Comment by gibhub-src** [comment]
Sorry, here are the charts with colored `Y-Axis-Title` according to #405.

**_1. LineChart03a - Extensive Chart Customization (Y-Axis Title color)_**
xchart-LineChart03a - Extensive Chart Customization (Y-Axis Title color)

**_2. DateChart01a - Millisecond Scale with Two Separate Y Axis Groups (title & color)_**
xchart-DateChart01a - Millisecond Scale with Two Separate Y Axis Groups (title   color)

3. DateChart03a - Minute Scale with Two Separate Y Axis Groups (titled & colored)
xchart-DateChart03a - Minute Scale with Two Separate Y Axis Groups (titled   colored)

**Comment by Mr14huashao** [comment]
@timmolter 
This PR has been replaced by PR #418 and has been modified as you suggested. This PR can be closed.

**Pull request closed without merging**
