### PR TITLE
Compile the xchart-demo with java 8 since it uses JDK methods from 8.

### PR DESCRIPTION
**Pull request by marshallpierce**
Specifically, `ChartStylePanel.getMethod()` uses `Method#getParameterCount()`.

### CODE REVIEW

**Comment by timmolter** [comment]
This is already defined in the parent POM. And it is set to 1.6.

**Comment by timmolter** [comment]
Where are Java 8 features used?

**Comment by marshallpierce** [comment]
> This is already defined in the parent POM. And it is set to 1.6.

That's why I'm overriding it in xchart-demo -- so it can be set differently. :)

Without this, IntelliJ (correctly) complains that [getParameterCount()](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Method.html#getParameterCount--) is Java 8+, but xchart-demo is set to use Java 6.

**Comment by timmolter** [comment]
Thanks for bringing this to light. I never noticed it before, but I can verify that IntelliJ complains to me about it too when I open the class:
Screen Shot 2019-05-04 at 09 41 43
Why would a Maven build successfully and IntelliJ not? I only recently upgraded to JDK 11, and I suspect that it has something to do with that.

Anyway, I think I'll bump the XChart project to Java 8 minimum.

**Comment by marshallpierce** [comment]
It's technically expressible to call that method with 1.6 bytecode, so the plain old java compiler doesn't object. A plugin like [animal sniffer](http://www.mojohaus.org/animal-sniffer/) should be able to notice such a thing though. IntelliJ has additional checks on top of what the compiler does.

Either way I'm fully on board with making it java 8 minimum. :)

**Pull request closed without merging**
