### PR TITLE
Mrcjkb/annotation auto detect color

### PR DESCRIPTION
**Pull request by MrcJkb**
This PR adds an API endpoint to `Styler` that allows the client to configure an auto-detection of the annotation font color based on the background color it is painted over.

An example is included with the demo bar chart BarChart13.

### CODE REVIEW

**Comment by timmolter** [comment]
This is very cool. I think this should be the default feature though and if people want to change it, they use the standard `setcolor` method in the styler.

**Comment by MrcJkb** [comment]
I would have to look into it.
It makes sense to make it the default behaviour for charts on which the annotations are always on top of the chart (like category charts and heat maps),. But it wouldn't make sense for pie charts with the annotations outside.

**Comment by MrcJkb** [comment]
I have set the default behaviour for category charts and disabled it for other types for now (as I don't know what side effects it will have due to the merge conflict resolution).

**Comment by timmolter** [comment]
Thanks. BTW, I'm calling the old "annotations" now "labels" to differentiate the from "Chart annotations". See the readme about what those are. I'm going to update your method names to reflect this change.

**Pull request merged**
