### PR TITLE
Adding Unit Test for the simplest example

### PR DESCRIPTION
**Pull request by mccartney**
Adding a simple Unit Regression Test for what is called "Simplest example" in the README.
The test renders the chart and compares (byte-to-byte) the outcome with pre-calculated result. The test is meant to catch regressions.

### CODE REVIEW

**Comment by mccartney** [comment]
If this test is accepted, I suggest to declare more of them - starting probably with all the code examples given in the `README.md`.

**Comment by mccartney** [comment]
```
testSimplestExampleStaysTheSame(org.knowm.xchart.regressiontests.SimplestExampleTest)  Time elapsed: 0.577 sec  <<< FAILURE!

arrays first differed at element [0]; expected:<79> but was:<53>
```
while the test passes locally for me.
So I am guessing there might be some non-determinism in the rendering - i.e. due to locale, machine type, etc.

**Comment by mccartney** [comment]
I've managed to reproduce. It's actually the font - OSX vs Linux.

See the zoomed example:
Linux: 
image

OSX: 
image

**Comment by mccartney** [comment]
Current code renders differently in OSX. The difference is subtile though.
online-image-comparison.com result:
image

**Comment by mccartney** [comment]
Following https://stackoverflow.com/a/28787211/118587 I've learned even when you ask for Arial you might get something else. And asking for Arial 14 on my Linux yields `Dialog.plain`, while on a OSX the answer is (a more reasonable) `ArialMT`. I wonder if there's any true font which is available in typical installations of OSX/Linux/Windows.

**Comment by timmolter** [comment]
Really cool! Learned something new!

**Pull request merged**
