### PR TITLE
Print chart from popup menu

### PR DESCRIPTION
**Pull request by tomassvensson**

### CODE REVIEW

**Comment by tomassvensson** [comment]
Any feedback on this? What would be needed to merge this commit?

**Comment by massimilianoporzio** [comment]
Please in a multi chart this will print the entire frame..can u please give the ability to print the single panel? (The sub plot)

**Comment by timmolter** [comment]
I'll take a look this weekend.

**Comment by timmolter** [comment]
whoops, nevermind...

**Pull request merged**
