### PR TITLE
Reworked: Customizable sum text for pie chart

### PR DESCRIPTION
**Pull request by tornaia**

### CODE REVIEW

**Comment by tornaia** [comment]
Is there anything I could do to have this change merged to master?

**Comment by tornaia** [comment]
Is there anything I could do to have this change merged to develop?

**Comment by timmolter** [comment]
Could you refactor this somehow so that you set a String rather than a SumFormatter. Then you can set a String like: `"Total: %.0f"`.

**Comment by tornaia** [comment]
I use this pie chart to visualize time and I'd like to show the sum somehow in human friendly way. 

image

With a string-ish solution I could just show something like this: "Total: 5956 seconds".

**Comment by timmolter** [comment]
I was going off your example code which uses the `"Total: %.0f"` formatter String. But you're saying a `SumFormatter` is even more flexible/powerful, right?

**Comment by tornaia** [comment]
Yes, its more flexible, that's the motivation of this PR. :)

**Comment by colm-costelloe** [comment]
Oops! Looks like I should have looked closer at this before I made my PULL request (https://github.com/knowm/XChart/pull/323)
My solution is practically identical to this where I added a `sumFormat` (MessageFormat string) in the `PieStyler` to customise the text to be drawn.

**Comment by timmolter** [comment]
I'll get to this soon hopefully

**Comment by timmolter** [comment]
I merged #323 instead.

**Pull request closed without merging**
