### PR TITLE
setXAxisMaxLabelCount() not to affect Y Axis in HeatMapCharts

### LINKED ISSUE #564: using setXAxisMaxLabelCount against a HeatMapChart alters both axes
One would expect `setXAxisMaxLabelCount()` only alters the number of labels of the X axis and doesn't affect the number for Y axis.
Yet in HeatMapCharts that's not true.

e.g.
```
        int N = 12;
        java.util.List<Integer> xData = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12);
        java.util.List<String> yData =
                Arrays.asList("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
        java.util.List<Number[]> data = new ArrayList<>();
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < N; j++) {
                data.add(new Integer[]{i, j, (i * 2 + j * 3) % 7});
            }
        }

        HeatMapChart chart = new HeatMapChart(800, 600);
        chart.addSeries("only", xData, yData, data);
        chart.getStyler().setTheme(new XChartTheme());
        chart.getStyler().setXAxisMaxLabelCount(5); // <---------------- they key line!
        BitmapEncoder.saveBitmap(chart, "/tmp/chart.png", BitmapEncoder.BitmapFormat.PNG);
```
yields
chart

### PR DESCRIPTION
**Pull request by mccartney**
Fixes #564.

Note that the unit test code looks somewhat ugly due to it using reflection to get to private fields (axisPair, yAxis). An alternative would be to increase the visibility for these two members. I am not sure if a unit test is a good enough reason for that.

### CODE REVIEW

**Comment by timmolter** [comment]
Let me look at it once I have a moment. Maybe we can increase the visibility.

**Comment by mccartney** [comment]
@timmolter any opinion on the unit test here?

**Comment by timmolter** [comment]
it looks like it made the build fail: https://github.com/knowm/XChart/runs/4121420139?check_suite_focus=true

**Comment by mccartney** [comment]
Yep. Looking into it. I wonder why didn't the branch-build catch it then?

**Pull request merged**
